/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stackcare_protobuf.proto */

#ifndef PROTOBUF_C_stackcare_5fprotobuf_2eproto__INCLUDED
#define PROTOBUF_C_stackcare_5fprotobuf_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MotionEvent MotionEvent;
typedef struct _ContactEvent ContactEvent;
typedef struct _ZoneStatus ZoneStatus;
typedef struct _AttributeReport AttributeReport;


/* --- enums --- */


/* --- messages --- */

/*
 * deprecated
 * TODO: remove
 */
struct  _MotionEvent
{
  ProtobufCMessage base;
  uint64_t report_time_epoch;
  protobuf_c_boolean has_delay;
  uint32_t delay;
  protobuf_c_boolean is_motion_detected;
};
#define MOTION_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&motion_event__descriptor) \
    , 0, 0, 0, 0 }


/*
 * deprecated
 * TODO: remove
 */
struct  _ContactEvent
{
  ProtobufCMessage base;
  uint64_t report_time_epoch;
  protobuf_c_boolean has_delay;
  uint32_t delay;
  protobuf_c_boolean alarmed;
};
#define CONTACT_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&contact_event__descriptor) \
    , 0, 0, 0, 0 }


struct  _ZoneStatus
{
  ProtobufCMessage base;
  uint64_t report_time_epoch;
  protobuf_c_boolean has_delay;
  uint32_t delay;
  uint32_t zone_status;
};
#define ZONE_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&zone_status__descriptor) \
    , 0, 0, 0, 0 }


struct  _AttributeReport
{
  ProtobufCMessage base;
  uint64_t report_time_epoch;
  protobuf_c_boolean has_delay;
  uint32_t delay;
  uint32_t cluster_id;
  uint32_t attribute_id;
  int32_t value;
};
#define ATTRIBUTE_REPORT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&attribute_report__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


/* MotionEvent methods */
void   motion_event__init
                     (MotionEvent         *message);
size_t motion_event__get_packed_size
                     (const MotionEvent   *message);
size_t motion_event__pack
                     (const MotionEvent   *message,
                      uint8_t             *out);
size_t motion_event__pack_to_buffer
                     (const MotionEvent   *message,
                      ProtobufCBuffer     *buffer);
MotionEvent *
       motion_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   motion_event__free_unpacked
                     (MotionEvent *message,
                      ProtobufCAllocator *allocator);
/* ContactEvent methods */
void   contact_event__init
                     (ContactEvent         *message);
size_t contact_event__get_packed_size
                     (const ContactEvent   *message);
size_t contact_event__pack
                     (const ContactEvent   *message,
                      uint8_t             *out);
size_t contact_event__pack_to_buffer
                     (const ContactEvent   *message,
                      ProtobufCBuffer     *buffer);
ContactEvent *
       contact_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   contact_event__free_unpacked
                     (ContactEvent *message,
                      ProtobufCAllocator *allocator);
/* ZoneStatus methods */
void   zone_status__init
                     (ZoneStatus         *message);
size_t zone_status__get_packed_size
                     (const ZoneStatus   *message);
size_t zone_status__pack
                     (const ZoneStatus   *message,
                      uint8_t             *out);
size_t zone_status__pack_to_buffer
                     (const ZoneStatus   *message,
                      ProtobufCBuffer     *buffer);
ZoneStatus *
       zone_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   zone_status__free_unpacked
                     (ZoneStatus *message,
                      ProtobufCAllocator *allocator);
/* AttributeReport methods */
void   attribute_report__init
                     (AttributeReport         *message);
size_t attribute_report__get_packed_size
                     (const AttributeReport   *message);
size_t attribute_report__pack
                     (const AttributeReport   *message,
                      uint8_t             *out);
size_t attribute_report__pack_to_buffer
                     (const AttributeReport   *message,
                      ProtobufCBuffer     *buffer);
AttributeReport *
       attribute_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   attribute_report__free_unpacked
                     (AttributeReport *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MotionEvent_Closure)
                 (const MotionEvent *message,
                  void *closure_data);
typedef void (*ContactEvent_Closure)
                 (const ContactEvent *message,
                  void *closure_data);
typedef void (*ZoneStatus_Closure)
                 (const ZoneStatus *message,
                  void *closure_data);
typedef void (*AttributeReport_Closure)
                 (const AttributeReport *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor motion_event__descriptor;
extern const ProtobufCMessageDescriptor contact_event__descriptor;
extern const ProtobufCMessageDescriptor zone_status__descriptor;
extern const ProtobufCMessageDescriptor attribute_report__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_stackcare_5fprotobuf_2eproto__INCLUDED */
