/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stackcare_protobuf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "stackcare_protobuf.pb-c.h"
void   motion_event__init
                     (MotionEvent         *message)
{
  static const MotionEvent init_value = MOTION_EVENT__INIT;
  *message = init_value;
}
size_t motion_event__get_packed_size
                     (const MotionEvent *message)
{
  assert(message->base.descriptor == &motion_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t motion_event__pack
                     (const MotionEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &motion_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t motion_event__pack_to_buffer
                     (const MotionEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &motion_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MotionEvent *
       motion_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MotionEvent *)
     protobuf_c_message_unpack (&motion_event__descriptor,
                                allocator, len, data);
}
void   motion_event__free_unpacked
                     (MotionEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &motion_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   contact_event__init
                     (ContactEvent         *message)
{
  static const ContactEvent init_value = CONTACT_EVENT__INIT;
  *message = init_value;
}
size_t contact_event__get_packed_size
                     (const ContactEvent *message)
{
  assert(message->base.descriptor == &contact_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t contact_event__pack
                     (const ContactEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &contact_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t contact_event__pack_to_buffer
                     (const ContactEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &contact_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ContactEvent *
       contact_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ContactEvent *)
     protobuf_c_message_unpack (&contact_event__descriptor,
                                allocator, len, data);
}
void   contact_event__free_unpacked
                     (ContactEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &contact_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   zone_status__init
                     (ZoneStatus         *message)
{
  static const ZoneStatus init_value = ZONE_STATUS__INIT;
  *message = init_value;
}
size_t zone_status__get_packed_size
                     (const ZoneStatus *message)
{
  assert(message->base.descriptor == &zone_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zone_status__pack
                     (const ZoneStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zone_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zone_status__pack_to_buffer
                     (const ZoneStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zone_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ZoneStatus *
       zone_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ZoneStatus *)
     protobuf_c_message_unpack (&zone_status__descriptor,
                                allocator, len, data);
}
void   zone_status__free_unpacked
                     (ZoneStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &zone_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   attribute_report__init
                     (AttributeReport         *message)
{
  static const AttributeReport init_value = ATTRIBUTE_REPORT__INIT;
  *message = init_value;
}
size_t attribute_report__get_packed_size
                     (const AttributeReport *message)
{
  assert(message->base.descriptor == &attribute_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t attribute_report__pack
                     (const AttributeReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &attribute_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t attribute_report__pack_to_buffer
                     (const AttributeReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &attribute_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AttributeReport *
       attribute_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AttributeReport *)
     protobuf_c_message_unpack (&attribute_report__descriptor,
                                allocator, len, data);
}
void   attribute_report__free_unpacked
                     (AttributeReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &attribute_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor motion_event__field_descriptors[3] =
{
  {
    "report_time_epoch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MotionEvent, report_time_epoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delay",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(MotionEvent, has_delay),
    offsetof(MotionEvent, delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_motion_detected",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MotionEvent, is_motion_detected),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned motion_event__field_indices_by_name[] = {
  1,   /* field[1] = delay */
  2,   /* field[2] = is_motion_detected */
  0,   /* field[0] = report_time_epoch */
};
static const ProtobufCIntRange motion_event__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor motion_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MotionEvent",
  "MotionEvent",
  "MotionEvent",
  "",
  sizeof(MotionEvent),
  3,
  motion_event__field_descriptors,
  motion_event__field_indices_by_name,
  2,  motion_event__number_ranges,
  (ProtobufCMessageInit) motion_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor contact_event__field_descriptors[3] =
{
  {
    "report_time_epoch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ContactEvent, report_time_epoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delay",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ContactEvent, has_delay),
    offsetof(ContactEvent, delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alarmed",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ContactEvent, alarmed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned contact_event__field_indices_by_name[] = {
  2,   /* field[2] = alarmed */
  1,   /* field[1] = delay */
  0,   /* field[0] = report_time_epoch */
};
static const ProtobufCIntRange contact_event__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor contact_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ContactEvent",
  "ContactEvent",
  "ContactEvent",
  "",
  sizeof(ContactEvent),
  3,
  contact_event__field_descriptors,
  contact_event__field_indices_by_name,
  2,  contact_event__number_ranges,
  (ProtobufCMessageInit) contact_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor zone_status__field_descriptors[3] =
{
  {
    "report_time_epoch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ZoneStatus, report_time_epoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delay",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ZoneStatus, has_delay),
    offsetof(ZoneStatus, delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zone_status",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ZoneStatus, zone_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned zone_status__field_indices_by_name[] = {
  1,   /* field[1] = delay */
  0,   /* field[0] = report_time_epoch */
  2,   /* field[2] = zone_status */
};
static const ProtobufCIntRange zone_status__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor zone_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ZoneStatus",
  "ZoneStatus",
  "ZoneStatus",
  "",
  sizeof(ZoneStatus),
  3,
  zone_status__field_descriptors,
  zone_status__field_indices_by_name,
  2,  zone_status__number_ranges,
  (ProtobufCMessageInit) zone_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor attribute_report__field_descriptors[5] =
{
  {
    "report_time_epoch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(AttributeReport, report_time_epoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delay",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(AttributeReport, has_delay),
    offsetof(AttributeReport, delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cluster_id",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AttributeReport, cluster_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attribute_id",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AttributeReport, attribute_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AttributeReport, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned attribute_report__field_indices_by_name[] = {
  3,   /* field[3] = attribute_id */
  2,   /* field[2] = cluster_id */
  1,   /* field[1] = delay */
  0,   /* field[0] = report_time_epoch */
  4,   /* field[4] = value */
};
static const ProtobufCIntRange attribute_report__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 2 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor attribute_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AttributeReport",
  "AttributeReport",
  "AttributeReport",
  "",
  sizeof(AttributeReport),
  5,
  attribute_report__field_descriptors,
  attribute_report__field_indices_by_name,
  2,  attribute_report__number_ranges,
  (ProtobufCMessageInit) attribute_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
